import practoImg from "./practology/practology.png";
import practoHero from "./practology/practo-hero.jpg";
import tanmay from "./tanmay.webp";
import amit from "./amit.webp";
import cms from "./cms.png";
import wtsp from "./whatsapp.svg"
import laproscopy from "./laproscopy/laproscopy.webp";
import urologyImg from "./urology/urology.webp"
import gynoImg from "./gyno/gyno.webp";
import astheticImg from "./asthetic/asthetic.webp";
import bg1 from './bgForBenefit1.png';
import bg2 from './bgForBenefit2.png';
import bg3 from './bgForBenefit3.png';
import bg4 from './bgForBenefit4.png';
import ncemi from './No-cost-EMI.png';
import hsptl from './1-day-hospitalization.png';
import insurance from './Support-in-insurance-claim.png';
import usfda from './USFDA-Approved-procedure.png';
import hdfc from "./no-cost-emi/HDFC_Bank_Logo.png"
import ashish from "./ashish.webp"
import rahul from "./rahul.webp"
import callGif from "./call.gif"
export { callGif, rahul, amit, practoImg, practoHero, tanmay, cms, wtsp, laproscopy, urologyImg, gynoImg, astheticImg, bg1, bg2, bg3, bg4, ncemi, hsptl, insurance, usfda, hdfc, ashish };